globalVariables(c("A",
                  "Q",
                  "X1",
                  "X2",
                  "category",
                  "date.downloaded",
                  "index.components",
                  "index.option",
                  "period",
                  "retrieve",
                  "type",
                  "value",
                  "x_fun",
                  "ohlc_fun",
                  "TTM",
                  "X",
                  "group",
                  "section",
                  "sub.section",
                  "adjusted",
                  "symbol..",
                  "data..",
                  "class..",
                  "Revenue USD Mil",
                  "Shares Mil",
                  "Operating Cash Flow USD Mil",
                  "Earnings Per Share USD",
                  "Price to Book",
                  "Price to Cash Flow",
                  "Price to Earnings",
                  "Price to Sales",
                  "Book Value Per Share * USD",
                  "Cash Flow Per Share USD",
                  "Revenue Per Share USD",
                  "Last.Trade.Date",
                  "Market.Capitalization",
                  "EBITDA",
                  "Percent.Change.From.52.week.Low",
                  "Percent.Change.From.50.day.Moving.Average",
                  "Percent.Change.From.200.day.Moving.Average",
                  "Change.in.Percent",
                  "Ex.Dividend.Date",
                  "Dividend.Pay.Date",
                  "Revenue"))
